version: '3.8'
services:
  server:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: server
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - LOG_LEVEL=${LOG_LEVEL}
      - STORAGE_PATH=${STORAGE_PATH}
    ports:
      - target: 8080
        published: ${SERVER_PORT}
        mode: host
    entrypoint: ["/bin/demo.sh"]

  client:
    depends_on:
      - server
    network_mode: host
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: client
    environment:
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - SERVER_PORT=${SERVER_PORT}
      - LOG_LEVEL=${LOG_LEVEL}
      - STORAGE_PATH=/app/files
    entrypoint: ["/bin/demo.sh"]